# Generated by Django 4.0.7 on 2022-10-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='token',
            field=models.CharField(max_length=550),
        ),
    ]
