# Generated by Django 4.0.7 on 2022-11-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
