version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn myapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  db:
    image: postgres:13
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
