# docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - backend

  db:
    image: postgres:13
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
