# Generated by Django 4.0.7 on 2022-10-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('supplier', 'supplier'), ('staff', 'staff')], default='customer', max_length=20),
        ),
    ]
