# Generated by Django 4.0.7 on 2022-10-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_required_date_alter_order_shipped_date_and_more'),
        ('user_auth', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='order.store'),
        ),
    ]
