# Generated by Django 4.0.7 on 2022-10-29 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='date_blacklisted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
