# Generated by Django 4.0.7 on 2022-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_product_order_customer_order_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='required_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
